# Generated by Django 5.0.6 on 2024-07-17 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='edited_at',
            new_name='updated_at',
        ),
    ]
