# Generated by Django 5.0.6 on 2024-08-06 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('OUTBID', 'Outbid'), ('WIN', 'Auction Win'), ('LOSING_BID', 'Losing Bid'), ('BID_PLACED', 'Bid Placed'), ('AUCTION_START', 'Auction started'), ('AUCTION_END', 'Auction ended'), ('SYSTEM_ALERT', 'System alert')], max_length=50)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
