# Generated by Django 5.0.6 on 2024-08-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_remove_customuser_otp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google')], default='local', max_length=10),
        ),
    ]
