# Generated by Django 5.0.6 on 2024-08-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_customuser_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile_picture.jpeg', null=True, upload_to='profile_pictures/'),
        ),
    ]
