# Generated by Django 5.0.6 on 2024-08-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.jpeg', null=True, upload_to='profile_pictures/'),
        ),
    ]
