# Generated by Django 5.1 on 2024-09-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_alter_customuser_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
