# Generated by Django 5.0.6 on 2024-08-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('PAYMENT', 'Payment'), ('TOPUP', 'Top-Up'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund'), ('AUCTION_SALE', 'Action_sale'), ('AUCTION_BUY_NOW', 'Auction_buy_now')], max_length=20),
        ),
    ]
