import React from 'react';
import { View, Text } from '@react-pdf/renderer';
import styles from './styles';

const Footer = () => (
	<View style={styles.footer}>
		<Text>Generated by Quick Bids</Text>
	</View>
);

export default Footer;
