# Generated by Django 5.0.6 on 2024-08-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_remove_payment_transaction_payment_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(choices=[('WALLET', 'Wallet'), ('RAZORPAY', 'Razorpay')], default='WALLET', max_length=10),
        ),
    ]
