# Generated by Django 5.0.6 on 2024-08-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_rename_timestamp_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(choices=[('WALLET', 'Wallet'), ('RAZORPAY', 'Razorpay')], default=('RAZORPAY', 'Razorpay'), max_length=10),
        ),
    ]
