# Generated by Django 5.1 on 2024-09-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0008_accountdetail_carddetail_upidetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='ifsc_code',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payments.accountdetail'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='card_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payments.carddetail'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='upi_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payments.upidetail'),
        ),
    ]
