# Generated by Django 5.1 on 2024-09-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0009_remove_withdrawalrequest_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
