# Generated by Django 5.1 on 2024-09-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0010_alter_accountdetail_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='type',
            field=models.CharField(choices=[('ACCOUNT', 'Account'), ('UPI', 'upi'), ('CARD', 'card')], default='ACCOUNT', max_length=10),
        ),
    ]
