# Generated by Django 5.1 on 2024-09-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0011_withdrawalrequest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetail',
            name='card_hash',
            field=models.CharField(default='123', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
