# Generated by Django 5.1 on 2024-09-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0012_carddetail_card_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='upidetail',
            name='upi_id_hash',
            field=models.CharField(default=123, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
