# Generated by Django 5.0.6 on 2024-08-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bids', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxybid',
            name='current_bid',
        ),
    ]
