# Generated by Django 5.0.6 on 2024-08-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bids', '0002_remove_proxybid_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxybid',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
