# Generated by Django 5.0.6 on 2024-08-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bids', '0003_proxybid_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxybid',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
